### ISSUE TITLE
Can not build with Angular 1.6.0

### ISSUE THREAD

**Issue by james-criscuolo** [outbrain/pure-angular-date-range-picker#27]
I just attempted to upgrade my application to angular 1.6.0. Upon page load, I get an error:

```
angular.min.js:122 TypeError: this.weekStart is not a function
    at new ObDateRangePickerController (ob-daterangepicker.js:875)
    at Object.invoke (angular.min.js:43)
    at Q.instance (angular.min.js:93)
    at p (angular.min.js:68)
    at angular.min.js:79
    at angular.min.js:133
    at m.$eval (angular.min.js:147)
    at m.$digest (angular.min.js:144)
    at m.$apply (angular.min.js:147)
    at angular.min.js:21
```

Which leads to this line (and there are many similar lines under it):

```
this.weekStart = this.weekStart() ? this.weekStart : function () {
  return dateRangePickerConf.weekStart;
};
```

I don't currently have time to make a PR, but wanted to push this back just in case somebody can take a look before I get a chance. At a glance, switching to:

```
this.weekStart = this.weekStart || function () { ... }
```

should fix, but it's possible that the issue has a worse problem.

While I have an issue here, I'd also like to point out in a previous PR I added angular as a dependency. It seems I was incorrect in doing that, and most angular-dependent projects actually don't do this, so my apologies on that one. If I get to making this PR, I'll likely include that removal.

**Comment by vlio20** [comment]
I am making a fix, thanks for the issue.

**Comment by vlio20** [comment]
the issue was resolved in 0.10.1 release. 
@james-criscuolo, it would be nice if you update and see if you have it working.

**Comment by james-criscuolo** [comment]
Just confirmed that this works, thanks for the quick turnaround!
